version: "3.8"

services:
    yg-mariadb:
        image: mariadb:10.7.1
        container_name: yg-mariadb
        restart: always
        volumes:
            - ./db/data/maria:/var/lib/mysql
        environment:
            - MYSQL_HOST=yg-mariadb
            - MYSQL_PORT=3306
            - MYSQL_ROOT_PASSWORD=ygenter
            - MYSQL_DATABASE=ygenter
            - MYSQL_USER=ygenter
            - MYSQL_PASSWORD=ygenter
        
    yg-mongodb:
        image: mongo:5.0.5
        container_name: yg-mongodb
        restart: always
        volumes:
            - ./db/data/mongo:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=ygenter
            - MONGO_INITDB_ROOT_PASSWORD=ygenter
            - MONGO_INITDB_DATABASE=ygenter
            - MONGO_PORT=27017

    yg-sentimental-analysis:
        image: sentimental-analysis
        container_name: yg-sentimental-analysis
#        deploy:
#            resources:
#                reservations:
#                    devices:
#                        - capabilities: [gpu]
        restart: always
        depends_on:
            - yg-mariadb
            - yg-mongodb          
        ports:
            - "0.0.0.0:8082:8000"
        command: >
            sh -c "python3 manage.py makemigrations &&
                   python3 manage.py migrate &&
                   python3 manage.py runserver 0.0.0.0:8000 --insecure"

#                   python3 manage.py migrate mongo &&
    yg-rabbitmq:
        image: rabbitmq:3.7.14-management-alpine
        container_name: yg-rabbitmq
        environment:
            - RABBITMQ_USER=ygenter
            - RABBITMQ_PASSWORD=ygenter
        ports:
            - "5672:5672"
            - "15672:15672"

    yg-celery-worker-beat:
        image: sentimental-analysis
        container_name: yg-celery-worker-beat
        command: celery -A crawler worker --beat -c 6 -l info
        ports: [ ]
        links:
            - yg-rabbitmq
        depends_on:
            - yg-rabbitmq
            - yg-mariadb